### ISSUE TITLE
[PocketGo2 v2 / RG350P] "Final Burn Alpha for OpenDingux/RG350" stays on screen and flickers after quitting FBA option menu while in game.

### ISSUE THREAD

**Issue by DrUm78** [goldmojo/fba-sdl#3]
Hardware: PocketGo2 v2 / RG350P
O/S: Rogue FW 1.0.9 for PocketGo2 v2 / Rogue FW 1.7.10 for RG350
Software: FinalBurnAlpha_2020-01-29-.44_alias_cmdline_gameconfig_controls_samples.opk

After exiting FBA menu during a game, "Final Burn Alpha for OpenDingux/RG350..." stays displayed on screen and flickers. The  workaround is to display fps (L+R+Y) then it disappears.
EDIT: This bug occurs only with "Vertical sync" set to ON and visible only with games whose pixel height is lower than 240 (otherwise the issue will be masked).

Steps to reproduce:
1. Launch any game that is NOT fullscreen (less than 240 pixels height) and with "Vertical sync" set to ON
2. Press L+R+Start to access FBA option menu
3. Exit this menu with B button
4. Notice that menu title stays on screen and flickers
5. Press L+R+Y
6. Notice that it fixed the issue

**Comment by goldmojo** [comment]
I can't reproduce this, could you name some specific roms ?

**Comment by DrUm78** [comment]
Any rom in fact, just look at this:
https://drive.google.com/file/d/14M7f5Tsnx1vs8Fb8fz_NcxN49c4yfhr2/view?usp=sharing

I simply display the menu with Power button during a game, then I press B to go back to the game then the text stays displayed on screen and flickers. L+R+Y fixes the issue.

Sorry for the camera shaking, hard to shoot with a smartphone while pressing buttons on my RG350P...

**Comment by goldmojo** [comment]
It is impossible to reproduce this one on my RG350 (rogue 1.7.10 + same FBA).

**Comment by DrUm78** [comment]
I reproduce it on PocketGo2 v2 as well. Maybe it's not on RG350 then, strange though. I tried quite a lot of roms and it's a general issue here.

**Comment by DrUm78** [comment]
Important note: to reproduce this bug, you need to play a game that is NOT fullscreen, otherwise game emulation will mask the issue. I only play my games with "Hardware scaling" set to "Off" so with Neo-Geo or CPS1/2 games, you will notice the issue as those systems are only 224 pixels height, not 240 as the RG350 screen is.

Sometimes the issue does not occur, you just have to display the menu again and you should be able to reproduce after 2 or 3 tries (it often happens).

EDIT: Found the guilty... vsync option in rom settings. No bug without vsync.

**Comment by goldmojo** [comment]
If you agree, I propose to close this one.
I should not be able to fix it.

**Comment by DrUm78** [comment]
No problem, I created the ticket on nobk git repo, just in case. Thanks.
